development:
  adapter: postgresql
  encoding: unicode
  database: app_dev
  pool: 5
  username: 'postgres'
  password: 'password'
  host: localhost
  
production:
  adapter: postgresql
  encoding: utf8
  database: app_production
  pool: 5
  username: 'postgres'
  password: 'password'
  host: localhost
  timeout: 5000