default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: app_development
test:
  <<: *default
  database: app_test
production:
  adapter: postgresql
  host: localhost
  username: 'postgres'
  password: 'password'
  timeout: 5000
  port: 5432
  database: app_production