<<<<<<< HEAD

=======
>>>>>>> ebd08c7ca640bd4f0ca740e4056c4f242e34d536
default: &default
  adapter: postgresql
  host: localhost
  username: 'postgres'
  password: 'password'
  timeout: 5000
  port: 5432
development:
  <<: *default
  database: app_development
test:
  <<: *default
  database: app_test
production:
  <<: *default
  database: app_production